services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network

  linux-build-server:
    build:
      context: ./linux_build_server
      dockerfile: Dockerfile
    container_name: linux-build-server
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
    entrypoint: /usr/sbin/sshd -D

  # linux-agent:
  #   image: jenkins/inbound-agent:latest
  #   container_name: linux-agent
  #   environment:
  #     JENKINS_URL: http://jenkins:8080
  #     JENKINS_AGENT_NAME: "linux-node"
  #     JENKINS_SECRET: "${JENKINS_SECRET}"
  #   networks:
  #     - jenkins-network
  #   depends_on:
  #     - jenkins

volumes:
  jenkins_home:

networks:
  jenkins-network:
